### ISSUE TITLE
danectl sshfp-check: disable SHA1 digest

### ISSUE THREAD

**Issue by HLFH** [raforg/danectl#9]
Depends slightly from `openssh`:

 - https://bugzilla.mindrot.org/show_bug.cgi?id=3494 ;
 - https://bugzilla.mindrot.org/show_bug.cgi?id=3493.

`danectl sshfp-check` should be able to recommend to:

 - publish only SHA-256 SSHFP fingerprints in the DNS ;
 - remove SHA1 SSHFP fingerprints in the DNS if present.

**Comment by raforg** [comment]
Hi, Thanks! I have my doubts that this is really a problem. It might just be "security theatre".

Since SSHFP records are in DNSSEC-signed zones, an attacker can't replace the IP address in the corresponding A/AAAA record to redirect ssh clients to a malicious server. So they'd have to compromise the real server, and so wouldn't need a different key that clashed with the original SHA1 hash, and most ssh clients that are capable of SHA-256 would probably verify with that hash anyway (I'm just guessing, and it's not required by RFC4255, but I'd be very surprised if they didn't).

But I suppose ISP routers could be hacked to rewrite/redirect the packets to a malicious server, and some ssh clients might verify with SHA1 even when they can verify with SHA-256 instead.

Luckily, if that threat is a concern, it's easy enough to only publish non-SHA1 records by piping danectl's output through grep:

    danectl sshfp-check DOMAIN | grep -v '[^;].*SSHFP.[0-9]\+ 1 '

That grep command will also allow notice of RRs that need to be removed to still appear. But they wouldn't appear until after the host key has been changed, so it's not ideal.

A better place to change this would be with ssh-keygen itself. If its authors agree with the bug reports, they'll probably fix the problem at the source. In the meantime, creating a wrapper script for ssh-keygen would fix it:

    #!/bin/sh
    /usr/bin/ssh-keygen "$@" | grep -v 'SSHFP [0-9]\+ 1 '

This could be added to danectl, but I wouldn't want to force it on anyone, or change the default behaviour (i.e. whatever ssh-keygen thinks is best). There would have to be a new option (or environment variable) to suppress SHA1.

I'd prefer it to be enabled via an environment variable (as it's a policy decision that should always apply), rather than a command line option (that the user would always need to remember to use). Also, if this becomes redundant because ssh-keygen gets changed, a vestigial command line option is more annoying to have around than a vestigial environment variable.

As an alternative, there could just be a `nosha1` script like this:

    #!/bin/sh
    # nosha1 - A filter to strip SHA1 SSHFP RRs from stdin
    exec grep -v '[^;].*SSHFP.[0-9]\+ 1 '

That would work with ssh-keygen, ssh-keyscan, and danectl:
 
    ssh-keygen -r NAME | nosha1
    ssh-keyscan -D NAME | nosha1
    danectl sshfp NAME | nosha1

It might be better to do that until ssh-keygen is changed.

How important to you is it that a fix appear in danectl itself, rather than via ssh-keygen?
I'd like to hear how the openssh team responds to those bug reports.

**Comment by HLFH** [comment]
The environment variable idea is interesting.

I am now using in `~/.zshrc` the `nosha1` alias:
```
# nosha1 - A filter to strip SHA1 SSHFP RRs from stdin
alias nosha1="grep -v '[^;].*SSHFP.[0-9]\+ 1 '"
```

Thanks!

Without `exec` because it weirdly makes me exit the SSH session.
> Connection to [...] closed

You may want to advertise the `nosha1` alias in the README?
I have now removed my SHA1 SSHFP RRs.

And we could close this issue because of this `nosha1` alias and the fact it is better to wait for `openssh` and `ssh-keygen` to implement the changes.

**Comment by raforg** [comment]
The `exec` only makes sense when `nosha1` is a `#!/bin/sh` script. It makes the `grep` process replace the `sh` process rather than leaving the `sh` process running (asleep) while `grep` is running. It makes sense to remove the `exec` for an alias.
